name: Deploy to Heroku

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v
        
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: "HEAD:main"
        
    - name: Run production health check
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        sleep 30
        curl -f ${{ secrets.HEROKU_API_URL }}/ || exit 1
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi
